### ISSUE TITLE
Test values and not only types

### ISSUE THREAD

**Issue by alexeyinkin** [stvndelucis/firestore_api_parser#8]
A lot of tests currently only expect the type but not the value.
Example:

https://github.com/stvndelucis/firestore_api_parser/blob/8f8f22ad4e4a9e8cf1f77847f4d74594ef1b50e7/test/firestore_to_json_test.dart#L123-L128

**Comment by stvndelucis** [comment]
Hello.
Sorry about that, probably an oversight on my part.  I'm off to do these tests

**Comment by stvndelucis** [comment]
All the tests for the values have been carried out and will be available in the next update.
